name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Build and Test
      run: |
        docker build -t my-node-app .
        docker run -d --name my-running-app -p 8888:8888 my-node-app
        sleep 10
        curl http://localhost:8888

    - name: Publish Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: my-node-app:latest

    - name: Clean up
      run: |
        docker stop my-running-app
        docker rm my-running-app
