name: Node-Express-Three.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Create tarball
      run: tar -czvf lottery.tar.gz --exclude='node_modules' .
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Push Docker image to container registry
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: my-image-name:$(date +%s)
    - name: Deploy Docker container to production
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          docker stop my-container-name || true
          docker rm my-container-name || true
          docker pull my-image-name:$(date +%s)
          docker run -d -p 8888:8888 --name my-container-name my-image-name:$(date +%s)
