name: lottery-game

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Package source code
        run: |
          tar -czvf lottery.tar.gz lottery/

      - name: Build Docker image
        run: |
          docker build -t lucky:v01 .

      - name: Docker Login
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image
        run: |
          docker tag lucky:v01 yiliangjianghu/luckygame:v01
          docker push yiliangjianghu/luckygame:v01

      - name: Run Docker container
        run: |
          docker run -d -p 28888:8888 --name luckyGame yiliangjianghu/luckygame:v01

      - name: Access service
