name: Lottery App CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.14.0'
      - name: Install dependencies
        run: |
          cd lottery/server && npm install
          cd ../product && npm install
      - name: Build app
        run: |
          cd lottery && sed -i '/openBrowser/ d' ./server/server.js
          cd product && npm run build
      - name: Start app
        run: |
          cd lottery/product && npm run serve
        env:
          PORT: 8888
    ports:
      - 8888:8888
